apiVersion: apps/v1
kind: Deployment
metadata: 
  name: flask_api
  labels:
    app: flask_api
spec: 
  replicas: 2
  selectors: 
    matchLabels: 
      app: flask
  template: 
    metadata: 
      labels:
        app: flask
    spec:
      containers:
      - image: scinet0786/background_api
        name:  flask_api
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service 
metadata: 
   name: flask_svc  
spec: 
  selector:
    app: flask_api
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 5000
    nodePort: 31000







